### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [HarukiGrande/GrandeCogs-V3#1]
After updating Red, NSFW no longer loads giving the error code: 

RuntimeError: The NSFW cog in the nsfw.nsfw package does not inherit from the commands.Cog base class. The cog auth
or must update the cog to adhere to this requirement.

**Comment by HarukiGrande** [comment]
Fixed by https://github.com/HarukiGrande/GrandeCogs-V3/pull/2
